FROM python:3.12

RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock* ./

RUN poetry config virtualenvs.create false \
    && poetry install --without dev --no-root --no-interaction --no-ansi --only main,backend

COPY . ./app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]