version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - qdrant
<<<<<<< HEAD
    network_mode: "host"

=======
    network_mode: 'host'
    
>>>>>>> e822b3a (added packages to poetry and added 'network_mode' to dockerfile (for hosting))
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
<<<<<<< HEAD
  qdrant_storage:
=======
  qdrant_storage: 
>>>>>>> e822b3a (added packages to poetry and added 'network_mode' to dockerfile (for hosting))
