FROM python:3.12

RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock* ./

# Install frontend dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi --only main,frontend

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]