FROM python:3.12

RUN pip install poetry

WORKDIR /app
COPY pyproject.toml poetry.lock* ./

# Install backend dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi --only main,backend

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]