[tool.poetry]
name = "hybridrag"
version = "0.1.0"
description = "Environment for running the HybridRAG project."
authors = ["Your Name <you@example.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.12, <3.13"
langchain = "^0.3.1"
langchain-community = "^0.3.1"
ipykernel = "^6.29.5"
pandas = "^2.2.3"
neo4j = "^5.25.0"
unstructured = "^0.15.13"
pypdf = "^5.0.1"
uvicorn = "^0.31.0"
fastapi = {extras = ["standard"], version = "^0.115.0"}
requests = "^2.32.3"
<<<<<<< HEAD
beautifulsoup4 = "^4.12.3"
lxml = "^5.3.0"
sentence-transformers = "^3.2.0"
qdrant-client = "^1.12.0"
=======
sentence-transformers = "^3.2.0"
qdrant-client = "^1.12.0"
lxml = "^5.3.0"
uuid = "^1.30"
>>>>>>> e822b3a (added packages to poetry and added 'network_mode' to dockerfile (for hosting))


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
